# Generated by Django 5.1.1 on 2024-11-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_teammember_positions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
