# Generated by Django 5.1.1 on 2024-11-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_task_date_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hours_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
